/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package visual.InfractionView;

import models.Driver;
import models.Infraction;
import services.ServicesLocator;
import visual.CustomTable;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author adian
 */
public class InfractionView extends javax.swing.JPanel {

    /**
     * Creates new form InfractionView
     */
    public InfractionView() {
        initComponents();
        setupTable();
    }
    private void setupTable() {
        // 1. Configurar datos
        List<String> columns = Arrays.asList(
                "Código", "Licencia", "Tipo",
                "Fecha", "Lugar", "Puntos", "Estado"
        );

        try {
            List<Infraction>driversBD = ServicesLocator.getInstance().getInfractionServices().getAllInfractions();
            Object[][] data =new Object[driversBD.size()][7];
            int pos=0;
            for (Infraction d : driversBD) {
                Object[] row = {d.getInfractionCode(),d.getLicenseId(),d.getViolationType(),d.getDate().toString(),d.getLocation(),"-"+d.getPoints(),d.getStatus()};
                data[pos]=row;
                pos++;
            }
            CustomTable customTable = getCustomTable(columns, data);

            // 4. Asignar al scroll pane
            jScrollPane2.setViewportView(customTable);

        } catch (Exception e) {
            throw new RuntimeException(e);
        }

    }

    private CustomTable getCustomTable(List<String> columns, Object[][] data) {
        CustomTable customTable = new CustomTable(columns, data);


        // 2. Crear tabla personalizada


        // 3. Configurar acción al hacer doble click
        customTable.setRowDoubleClickListener(row -> {
            String info = "Información del Conductor:\n\n" +
                    "Nombre: " + customTable.getValueAt(row, 0) + "\n" +
                    "Documento: " + customTable.getValueAt(row, 1) + "\n" +
                    "Fecha Nacimiento: " + customTable.getValueAt(row, 2) + "\n" +
                    "Teléfono: " + customTable.getValueAt(row, 3) + "\n" +
                    "Estado Licencia: " + customTable.getValueAt(row, 4);

            JOptionPane.showMessageDialog(
                    this,
                    info,
                    "Detalles del Conductor",
                    JOptionPane.INFORMATION_MESSAGE
            );
        });
        return customTable;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleLabel = new javax.swing.JLabel();
        SearchTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        AddDriversButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(23, 22, 28));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TitleLabel.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        TitleLabel.setForeground(new java.awt.Color(255, 215, 179));
        TitleLabel.setText("Gestion de Infracciones");
        add(TitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 600, 40));

        SearchTextField.setBackground(new java.awt.Color(47, 50, 65));
        SearchTextField.setForeground(new java.awt.Color(153, 153, 153));
        SearchTextField.setText("Buscar infraccion...");
        SearchTextField.setBorder(null);
        SearchTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchTextFieldMouseClicked(evt);
            }
        });
        SearchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchTextFieldActionPerformed(evt);
            }
        });
        add(SearchTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 50, 230, 40));

        jLabel1.setBackground(new java.awt.Color(47, 50, 65));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utils/Icons/icons8-búsqueda-30.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 50, 40, 40));

        AddDriversButton.setBackground(new java.awt.Color(232, 152, 70));
        AddDriversButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        AddDriversButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utils/Icons/icons8-más-30.png"))); // NOI18N
        AddDriversButton.setText("   Nueva Infraccion");
        AddDriversButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDriversButtonActionPerformed(evt);
            }
        });
        add(AddDriversButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 50, 200, 40));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 215, 179));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utils/Icons/icons8-calendario-24.png"))); // NOI18N
        jLabel2.setText("Periodo:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 100, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        jScrollPane2.setViewportView(jTable1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 1250, 850));
    }// </editor-fold>//GEN-END:initComponents

    private void SearchTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchTextFieldMouseClicked
        SearchTextField.setText("");
    }//GEN-LAST:event_SearchTextFieldMouseClicked

    private void SearchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTextFieldActionPerformed

    }//GEN-LAST:event_SearchTextFieldActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        SearchTextField.requestFocusInWindow();
        SearchTextField.setText("");
    }//GEN-LAST:event_jLabel1MouseClicked

    private void AddDriversButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDriversButtonActionPerformed

    }//GEN-LAST:event_AddDriversButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddDriversButton;
    private javax.swing.JTextField SearchTextField;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
