/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visual.MainScreen;

import visual.DriverView.DriversView;
import visual.ExamView.ExamView;
import visual.InfractionView.InfractionView;
import visual.LicensView.LicensView;
import visual.MainView.MainView;
import java.awt.BorderLayout;

/**
 *
 * @author adian
 */
public class MainScreem extends javax.swing.JFrame {

    /**
     * Creates new form MainScreem
     */
    public MainScreem() {
        initComponents();
        MainView p1 = new MainView();
        p1.setSize(1560, 1050);
        p1.setLocation(0,0);
        
        Content.removeAll();
        Content.add(p1,BorderLayout.CENTER);
        Content.revalidate();
        Content.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        SideBar = new javax.swing.JPanel();
        InfractionButton = new javax.swing.JButton();
        DriversButton = new javax.swing.JButton();
        LicensButton = new javax.swing.JButton();
        ExamButton = new javax.swing.JButton();
        HomeButton = new javax.swing.JButton();
        Content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainPanel.setBackground(new java.awt.Color(23, 22, 28));
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SideBar.setBackground(new java.awt.Color(47, 50, 65));
        SideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InfractionButton.setBackground(new java.awt.Color(47, 50, 65));
        InfractionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/Icons/icons8-error-50.png"))); // NOI18N
        InfractionButton.setToolTipText("");
        InfractionButton.setBorder(null);
        InfractionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InfractionButtonMouseClicked(evt);
            }
        });
        InfractionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfractionButtonActionPerformed(evt);
            }
        });
        SideBar.add(InfractionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 90, 45));

        DriversButton.setBackground(new java.awt.Color(47, 50, 65));
        DriversButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/Icons/icons8-grupos-de-usuarios-50.png"))); // NOI18N
        DriversButton.setToolTipText("");
        DriversButton.setBorder(null);
        DriversButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DriversButtonMouseClicked(evt);
            }
        });
        DriversButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DriversButtonActionPerformed(evt);
            }
        });
        SideBar.add(DriversButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 90, 45));

        LicensButton.setBackground(new java.awt.Color(47, 50, 65));
        LicensButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/Icons/icons8-licencia-50.png"))); // NOI18N
        LicensButton.setToolTipText("");
        LicensButton.setBorder(null);
        LicensButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LicensButtonMouseClicked(evt);
            }
        });
        LicensButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LicensButtonActionPerformed(evt);
            }
        });
        SideBar.add(LicensButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 90, 45));

        ExamButton.setBackground(new java.awt.Color(47, 50, 65));
        ExamButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/Icons/icons8-examen-50.png"))); // NOI18N
        ExamButton.setToolTipText("");
        ExamButton.setBorder(null);
        ExamButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExamButtonMouseClicked(evt);
            }
        });
        ExamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExamButtonActionPerformed(evt);
            }
        });
        SideBar.add(ExamButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 90, 45));

        HomeButton.setBackground(new java.awt.Color(47, 50, 65));
        HomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/Icons/icons8-casa-45.png"))); // NOI18N
        HomeButton.setToolTipText("");
        HomeButton.setBorder(null);
        HomeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeButtonMouseClicked(evt);
            }
        });
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });
        SideBar.add(HomeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 90, 45));

        MainPanel.add(SideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 1050));

        Content.setBackground(new java.awt.Color(23, 22, 28));
        MainPanel.add(Content, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 1560, 1050));

        getContentPane().add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1690, 1050));

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void InfractionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfractionButtonActionPerformed
        
    }//GEN-LAST:event_InfractionButtonActionPerformed

    private void DriversButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DriversButtonActionPerformed
       
    }//GEN-LAST:event_DriversButtonActionPerformed

    private void ExamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExamButtonActionPerformed
       
    }//GEN-LAST:event_ExamButtonActionPerformed

    private void DriversButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DriversButtonMouseClicked
        DriversView p2 = new DriversView();
        p2.setSize(1560, 1050);
        p2.setLocation(0,0);
        
        Content.removeAll();
        Content.add(p2,BorderLayout.CENTER);
        Content.revalidate();
        Content.repaint();
    }//GEN-LAST:event_DriversButtonMouseClicked

    private void HomeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeButtonMouseClicked
        MainView p1 = new MainView();
        p1.setSize(1560, 1050);
        p1.setLocation(0,0);
        
        Content.removeAll();
        Content.add(p1,BorderLayout.CENTER);
        Content.revalidate();
        Content.repaint();
    }//GEN-LAST:event_HomeButtonMouseClicked

    private void LicensButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LicensButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LicensButtonActionPerformed

    private void LicensButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LicensButtonMouseClicked
        LicensView p3 = new LicensView();
        p3.setSize(1560, 1050);
        p3.setLocation(0,0);
        
        Content.removeAll();
        Content.add(p3,BorderLayout.CENTER);
        Content.revalidate();
        Content.repaint();
        
    }//GEN-LAST:event_LicensButtonMouseClicked

    private void ExamButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExamButtonMouseClicked
        ExamView p4 = new ExamView();
        p4.setSize(1560, 1050);
        p4.setLocation(0,0);
        
        Content.removeAll();
        Content.add(p4,BorderLayout.CENTER);
        Content.revalidate();
        Content.repaint();
    }//GEN-LAST:event_ExamButtonMouseClicked

    private void InfractionButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InfractionButtonMouseClicked
        // TODO add your handling code here:
        InfractionView p5 = new InfractionView();
        p5.setSize(1560, 1050);
        p5.setLocation(0,0);
        
        Content.removeAll();
        Content.add(p5,BorderLayout.CENTER);
        Content.revalidate();
        Content.repaint();
    }//GEN-LAST:event_InfractionButtonMouseClicked

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content;
    private javax.swing.JButton DriversButton;
    private javax.swing.JButton ExamButton;
    private javax.swing.JButton HomeButton;
    private javax.swing.JButton InfractionButton;
    private javax.swing.JButton LicensButton;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel SideBar;
    // End of variables declaration//GEN-END:variables
}
