package visual.DriverView;

import models.Driver;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;
import services.ServicesLocator;
import utils.Validations;
import visual.JtextFielCarnet;
import visual.MainScreen.MainScreen;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import java.util.Date;
import java.util.Objects;

public class AddDriver extends javax.swing.JDialog {
    /**
     * Creates new form AddDriver
     */
    public AddDriver(MainScreen parent) {
        super(parent, true);
        initComponents(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    private void initComponents(MainScreen father) {

        jPanel1 = new JPanel();
        TitleLabel = new JLabel();
        jLabel1 = new JLabel();
        phoneTextField = new JTextField();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        carnetIDJTextField1 = new JtextFielCarnet();
        emailjTextField = new JTextField();
        jLabel4 = new JLabel();
        firstNamejTextField = new JTextField();
        lastNameTextField = new JTextField();
        jLabel5 = new JLabel();
        addressjTextField = new JTextField();
        jLabel6 = new JLabel();
        deletejButton = new JButton();
        AddjButton1 = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new Color(23, 22, 28));
        setUndecorated(true);
        getContentPane().setLayout(new AbsoluteLayout());

        jPanel1.setBackground(new Color(23, 22, 28));
        jPanel1.setLayout(new AbsoluteLayout());

        TitleLabel.setFont(new Font("Arial Black", 1, 24)); // NOI18N
        TitleLabel.setForeground(new Color(255, 215, 179));
        TitleLabel.setText("Añadir Conductor");
        jPanel1.add(TitleLabel, new AbsoluteConstraints(220, 20, 260, 40));

        jLabel1.setFont(new Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new Color(255, 215, 179));
        jLabel1.setText("Correo: ");
        jPanel1.add(jLabel1, new AbsoluteConstraints(390, 330, -1, -1));

        phoneTextField.setBackground(new Color(47, 50, 65));
        phoneTextField.setForeground(new Color(204, 204, 204));
        phoneTextField.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                phoneTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(phoneTextField, new AbsoluteConstraints(50, 360, 230, 40));

        jLabel2.setFont(new Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new Color(255, 215, 179));
        jLabel2.setText("Teléfono:");
        jPanel1.add(jLabel2, new AbsoluteConstraints(50, 330, -1, -1));

        jLabel3.setFont(new Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new Color(255, 215, 179));
        jLabel3.setText("Carnet de Identidad:");
        jPanel1.add(jLabel3, new AbsoluteConstraints(50, 90, -1, -1));

        carnetIDJTextField1.setBackground(new Color(47, 50, 65));
        carnetIDJTextField1.setLimite(11);
        carnetIDJTextField1.setForeground(new Color(204, 204, 204));
        carnetIDJTextField1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                carnetIDJTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(carnetIDJTextField1, new AbsoluteConstraints(50, 120, 230, 40));

        emailjTextField.setBackground(new Color(47, 50, 65));
        emailjTextField.setForeground(new Color(204, 204, 204));
        emailjTextField.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                emailjTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(emailjTextField, new AbsoluteConstraints(390, 360, 230, 40));

        jLabel4.setFont(new Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new Color(255, 215, 179));
        jLabel4.setText("Nombre:");
        jPanel1.add(jLabel4, new AbsoluteConstraints(390, 90, -1, -1));

        firstNamejTextField.setBackground(new Color(47, 50, 65));
        firstNamejTextField.setForeground(new Color(204, 204, 204));
        firstNamejTextField.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                firstNamejTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(firstNamejTextField, new AbsoluteConstraints(390, 120, 230, 40));

        lastNameTextField.setBackground(new Color(47, 50, 65));
        lastNameTextField.setForeground(new Color(204, 204, 204));
        lastNameTextField.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                lastNameTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(lastNameTextField, new AbsoluteConstraints(50, 240, 230, 40));

        jLabel5.setFont(new Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new Color(255, 215, 179));
        jLabel5.setText("Apellido:");
        jPanel1.add(jLabel5, new AbsoluteConstraints(50, 210, -1, -1));

        addressjTextField.setBackground(new Color(47, 50, 65));
        addressjTextField.setForeground(new Color(204, 204, 204));
        addressjTextField.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                addressjTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(addressjTextField, new AbsoluteConstraints(390, 240, 230, 40));

        jLabel6.setFont(new Font("Arial", 0, 14)); // NOI18N
        jLabel6.setForeground(new Color(255, 215, 179));
        jLabel6.setText("Dirección:");
        jPanel1.add(jLabel6, new AbsoluteConstraints(390, 210, -1, -1));

        deletejButton.setForeground(new Color(153, 0, 0));
        deletejButton.setText("Salir");
        deletejButton.setFocusable(false);
        deletejButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                deletejButtonActionPerformed(evt);
            }
        });
        jPanel1.add(deletejButton, new AbsoluteConstraints(390, 470, 120, 30));

        AddjButton1.setBackground(new Color(232, 152, 70));
        AddjButton1.setText("Añadir");
        AddjButton1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                String carnetID = carnetIDJTextField1.getText();
                String email = emailjTextField.getText();
                String firstName = firstNamejTextField.getText();
                String lastName = lastNameTextField.getText();
                String address = addressjTextField.getText();
                String phone = phoneTextField.getText();
                Date fechaActual = new Date(2020, 8, 1);
                java.sql.Date fechaSQL = new java.sql.Date(fechaActual.getTime());
                if(carnetID!=null && !Objects.equals(email, "") && !Objects.equals(firstName, "") && !Objects.equals(lastName, "") && !Objects.equals(address, "") && !Objects.equals(phone, "")){
                    if (carnetID.length()==carnetIDJTextField1.getLimite()){
                        if(Validations.validarCarnet(carnetID)){
                            if(!Validations.nameValidation(firstName)){
                                try{
                                    //int driverId, String firstName, String lastName, Date birthDate,
                                    //                  String address, String phone, String email
                                   int carnet = Integer.parseInt(carnetID);
                                    ServicesLocator.getInstance().getDriverServices().createDriver(new Driver(carnet,firstName,lastName,fechaSQL,address,phone,email));
                                    father.Actualizar(1);
                                    dispose();

                                }
                                catch(Exception e){
                                    JOptionPane.showMessageDialog(null, e.getMessage(),"", JOptionPane.INFORMATION_MESSAGE);
                                }
                            }
                            else{
                                JOptionPane.showMessageDialog(null, "El nombre introducido no es correcto","", JOptionPane.INFORMATION_MESSAGE);
                            }
                        }
                        else{
                            JOptionPane.showMessageDialog(null, "El carnet de identidad introducido no es valido","", JOptionPane.INFORMATION_MESSAGE);
                        }
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "Algunas casillas estan vacias por favor rellene todos los campos","", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        });
        jPanel1.add(AddjButton1, new AbsoluteConstraints(160, 470, 120, 30));

        getContentPane().add(jPanel1, new AbsoluteConstraints(-20, 0, 680, 560));
        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>

    private void phoneTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void carnetIDJTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void emailjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void firstNamejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void lastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void addressjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void deletejButtonActionPerformed(java.awt.event.ActionEvent evt) {
        int respuesta= JOptionPane.showConfirmDialog(null, "Está seguro que desea cerrar esta ventana?", "Confirmar", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(respuesta==0){
            dispose();
        }
    }

    private void AddjButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }
    // Variables declaration - do not modify
    private javax.swing.JButton AddjButton1;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JTextField addressjTextField;
    private JtextFielCarnet carnetIDJTextField1;
    private javax.swing.JButton deletejButton;
    private javax.swing.JTextField emailjTextField;
    private javax.swing.JTextField firstNamejTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JTextField phoneTextField;
}
