package visual.RelatedEntityView;


import models.Driver;
import models.RelatedEntity;
import report.PDFReportGenerator;
import services.ServicesLocator;
import visual.CustomTable;
import visual.LicenseView.AddLicense;

import javax.swing.*;
import java.awt.*;
import java.io.File;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;

public class SelectRelatedEntity extends javax.swing.JDialog {

    /**
     * Creates new form SelectDriver
     */
    public SelectRelatedEntity(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        selectButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        customTable = new CustomTable();
        TitleLabel = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(23, 22, 28));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(23, 22, 28));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        selectButton.setBackground(new java.awt.Color(232, 152, 70));
        selectButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        selectButton.setText("Selecionar");
        selectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(selectButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 130, 30));

        List<String> columns = Arrays.asList(
                "Nombre", "Tipo", "Direccion",
                "Teléfono", "Correo","Director"
        );

        try {
            List<RelatedEntity>re = ServicesLocator.getInstance().getRelatedEntityServices().getAllRelatedEntities();
            Object[][] data =new Object[re.size()][6];
            int pos=0;
            for (RelatedEntity d : re) {
                Object[] row = {d.getEntityName(), d.getEntityType(),d.getAddress(),d.getPhone(),d.getContactEmail(),d.getDirectorName()};
                data[pos]=row;
                pos++;
            }
            customTable = new CustomTable(columns, data);
            customTable.getTableHeader().setReorderingAllowed(false);

            // 4. Asignar al scroll pane
            jScrollPane1.setViewportView(customTable);

        } catch (Exception e) {
            throw new RuntimeException(e);
        }


        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 700, 430));

        TitleLabel.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        TitleLabel.setForeground(new java.awt.Color(255, 215, 179));
        TitleLabel.setText("Seleccione una Entidad");
        jPanel1.add(TitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 600, 40));

        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 0, 0));
        jButton2.setText("Salir");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, 130, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 620));

        pack();
    }// </editor-fold>

    private void selectButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        int select = customTable.getSelectedRow();
        System.out.println("Fila: "+ select);
        if(select!=-1){
            String entity= (String) customTable.getValueAt(select,0);
            RelatedEntity re = null;
            try {
                re = ServicesLocator.getInstance().getRelatedEntityServices().obtainRelatedEntity(entity);
                if (re != null) {
                    try {
                        String pdfPath = PDFReportGenerator.createRelatedEntityReportPDF(re.getEntityName());

                        File file = new File(pdfPath);
                        if (file.exists()) {
                            Desktop.getDesktop().open(file);
                        } else {
                            throw new UnsupportedOperationException("El archivo no existe.");
                        }
                    } catch (IOException e) {

                        JOptionPane.showMessageDialog(null, "Hubo un problema al crear el reporte.");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "La entidad no existe.");
                }
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una Entidad");
        }

    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        dispose();
    }


    // Variables declaration - do not modify
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JButton selectButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private CustomTable customTable;
    // End of variables declaration
}
