/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package visual;

import report.PDFReportGenerator;

import javax.swing.JOptionPane;
import java.awt.*;
import java.io.File;
import java.io.IOException;
import java.util.Date;

/**
 *
 * @author adian
 */
public class PeriodTimeChooser extends javax.swing.JDialog {

    /**
     * Creates new form AddLicense
     */
    public PeriodTimeChooser(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TitleLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        AcceptjButton1 = new javax.swing.JButton();
        deletejButton = new javax.swing.JButton();
        beginDate = new com.toedter.calendar.JDateChooser();
        endDate = new com.toedter.calendar.JDateChooser();

        beginDate.addPropertyChangeListener(this::beginDatePropertyChange);
        endDate.addPropertyChangeListener(this::endDatePropertyChange);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(23, 22, 28));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TitleLabel.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        TitleLabel.setForeground(new java.awt.Color(255, 215, 179));
        TitleLabel.setText("Periodo de Tiempo");
        jPanel1.add(TitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 260, 40));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 215, 179));
        jLabel3.setText("Fecha fin:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 215, 179));
        jLabel7.setText("Fecha inicio:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 215, 179));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 230, 40));

        jLabel2.setForeground(new java.awt.Color(255, 215, 179));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 230, 40));

        jLabel4.setForeground(new java.awt.Color(255, 215, 179));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 230, 40));

        AcceptjButton1.setBackground(new java.awt.Color(232, 152, 70));
        AcceptjButton1.setText("Aceptar");
        AcceptjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddjButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(AcceptjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 120, 30));

        deletejButton.setForeground(new java.awt.Color(153, 0, 0));
        deletejButton.setText("Salir");
        deletejButton.setFocusable(false);
        deletejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletejButtonActionPerformed(evt);
            }
        });
        jPanel1.add(deletejButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 120, 30));
        jPanel1.add(beginDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 190, 40));
        jPanel1.add(endDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 210, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 400));

        pack();
    }// </editor-fold>

    private void AddjButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        Date beginDate = this.beginDate.getDate();
        Date endDate = this.endDate.getDate();

        if (beginDate == null || endDate == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar ambas fechas.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (beginDate.after(endDate)) {
            JOptionPane.showMessageDialog(this, "La fecha de inicio debe ser anterior a la fecha de fin.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {

            java.sql.Date start = new java.sql.Date(beginDate.getTime());
            java.sql.Date end = new java.sql.Date(endDate.getTime());
            try {
                String pdfPath = PDFReportGenerator.createLicenseReportPDF(start, end);

                File file = new File(pdfPath);
                if (file.exists()) {
                    Desktop.getDesktop().open(file);
                } else {
                    throw new UnsupportedOperationException("El archivo no existe.");
                }
            } catch (IOException e) {

                JOptionPane.showMessageDialog(null, "Hubo un problema al crear el reporte.");
            }
        }
    }

    private void deletejButtonActionPerformed(java.awt.event.ActionEvent evt) {
        int respuesta=JOptionPane.showConfirmDialog(null, "Está seguro que desea cerrar esta ventana?", "Confirmar", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(respuesta==0){
            dispose();
        }
    }

    private void beginDatePropertyChange(java.beans.PropertyChangeEvent evt) {
        if ("date".equals(evt.getPropertyName())) {
            Date fechaInicio = beginDate.getDate();
            if (fechaInicio != null) {
                endDate.setMinSelectableDate(fechaInicio); // Restringe selección en endDate
            }
        }
    }

    private void endDatePropertyChange(java.beans.PropertyChangeEvent evt) {
        if ("date".equals(evt.getPropertyName())) {
            Date fechaFin = endDate.getDate();
            if (fechaFin != null) {
                beginDate.setMaxSelectableDate(fechaFin); // Restringe selección en beginDate
            }
        }
    }

    // Variables declaration - do not modify
    private javax.swing.JButton AcceptjButton1;
    private javax.swing.JLabel TitleLabel;
    private com.toedter.calendar.JDateChooser beginDate;
    private javax.swing.JButton deletejButton;
    private com.toedter.calendar.JDateChooser endDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration
}
