/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package visual.MainView;

import models.License;
import services.ServicesLocator;

import java.util.ArrayList;

/**
 *
 * @author adian
 */
public class MainView extends javax.swing.JPanel {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleLabel = new javax.swing.JLabel();
        IDriverPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        DriversPanel_Icon1 = new javax.swing.JLabel();
        IDriversPanel_Title1 = new javax.swing.JLabel();
        IDriversPanel_Data1 = new javax.swing.JLabel();
        IDriverPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        DriversPanel_Icon = new javax.swing.JLabel();
        IDriversPanel_Title = new javax.swing.JLabel();
        IDriversPanel_Data = new javax.swing.JLabel();
        IDriverPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        DriversPanel_Icon2 = new javax.swing.JLabel();
        IDriversPanel_Title2 = new javax.swing.JLabel();
        IDriversPanel_Data2 = new javax.swing.JLabel();
        IInfractionPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        DriversPanel_Icon3 = new javax.swing.JLabel();
        IDriversPanel_Title3 = new javax.swing.JLabel();
        IDriversPanel_Data3 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(23, 22, 28));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TitleLabel.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        TitleLabel.setForeground(new java.awt.Color(255, 215, 179));
        TitleLabel.setText("Sistema de Gestion de Licencia");
        add(TitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 600, 40));

        IDriverPanel6.setBackground(new java.awt.Color(47, 50, 65));
        IDriverPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        IDriverPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        DriversPanel_Icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utils/Icons/icons8-grupos-de-usuarios-50 (1).png"))); // NOI18N
        IDriverPanel6.add(DriversPanel_Icon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        IDriversPanel_Title1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        IDriversPanel_Title1.setForeground(new java.awt.Color(255, 215, 179));
        IDriversPanel_Title1.setText("     Conductores");
        IDriversPanel_Title1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        IDriverPanel6.add(IDriversPanel_Title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 130, -1));

        IDriversPanel_Data1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        IDriversPanel_Data1.setForeground(new java.awt.Color(255, 215, 179));
        int cantDrivers=0;
        try {
            cantDrivers= ServicesLocator.getInstance().getDriverServices().countDrivers();
        }
        catch(Exception e) {
            e.printStackTrace();
        }
        IDriversPanel_Data1.setText("   "+cantDrivers+ " registrados");
        IDriverPanel6.add(IDriversPanel_Data1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 100, -1));

        add(IDriverPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 275, 150));


        IDriverPanel5.setBackground(new java.awt.Color(47, 50, 65));
        IDriverPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        IDriverPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        DriversPanel_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utils/Icons/icons8-licencia-50 (1).png"))); // NOI18N
        IDriverPanel5.add(DriversPanel_Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));


        IDriversPanel_Title.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        IDriversPanel_Title.setForeground(new java.awt.Color(255, 215, 179));
        IDriversPanel_Title.setText("       Licencias");
        IDriversPanel_Title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        IDriverPanel5.add(IDriversPanel_Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 130, -1));


        IDriversPanel_Data.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        IDriversPanel_Data.setForeground(new java.awt.Color(255, 215, 179));
        int cantLicenses=0;
        try{
            cantLicenses= ServicesLocator.getInstance().getLicenseServices().countLicenses();
        }
        catch(Exception e) {
            e.printStackTrace();
        }
        IDriversPanel_Data.setText("   "+cantLicenses+" emitidas");
        IDriverPanel5.add(IDriversPanel_Data, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 100, -1));

        add(IDriverPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 170, 275, 150));


        IDriverPanel7.setBackground(new java.awt.Color(47, 50, 65));
        IDriverPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        IDriverPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        DriversPanel_Icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utils/Icons/icons8-examen-50 (1).png"))); // NOI18N
        IDriverPanel7.add(DriversPanel_Icon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        IDriversPanel_Title2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        IDriversPanel_Title2.setForeground(new java.awt.Color(255, 215, 179));
        IDriversPanel_Title2.setText("       Exámenes");
        IDriversPanel_Title2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        IDriverPanel7.add(IDriversPanel_Title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 130, -1));

        IDriversPanel_Data2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        IDriversPanel_Data2.setForeground(new java.awt.Color(255, 215, 179));
        int cantText=0;
        try{
            cantText= ServicesLocator.getInstance().getTestServices().countTests();
        }
        catch(Exception e) {
            e.printStackTrace();
        }
        IDriversPanel_Data2.setText(" "+cantText+ " realizados");
        IDriverPanel7.add(IDriversPanel_Data2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 100, -1));

        add(IDriverPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 170, 275, 150));

        IInfractionPanel.setBackground(new java.awt.Color(47, 50, 65));
        IInfractionPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        IInfractionPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        DriversPanel_Icon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utils/Icons/icons8-error-50 (1).png"))); // NOI18N
        IInfractionPanel.add(DriversPanel_Icon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));


        IDriversPanel_Title3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        IDriversPanel_Title3.setForeground(new java.awt.Color(255, 215, 179));
        IDriversPanel_Title3.setText("     Infracciones");
        IDriversPanel_Title3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        IInfractionPanel.add(IDriversPanel_Title3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 130, -1));

        IDriversPanel_Data3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        IDriversPanel_Data3.setForeground(new java.awt.Color(255, 215, 179));
        int cantInfraction=0;
        try{
            cantInfraction= ServicesLocator.getInstance().getInfractionServices().countInfractions();
        }
        catch(Exception e) {
            e.printStackTrace();
        }
        IDriversPanel_Data3.setText("  "+cantInfraction+ " registradas");
        IInfractionPanel.add(IDriversPanel_Data3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 100, -1));

        add(IInfractionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1025, 170, 275, 150));


    }// </editor-fold>//GEN-END:initComponents

    private void ExpireLicensPanel_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpireLicensPanel_ButtonActionPerformed

    }//GEN-LAST:event_ExpireLicensPanel_ButtonActionPerformed

    private void RecentInfractionPanel_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecentInfractionPanel_Button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RecentInfractionPanel_Button1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables

    private javax.swing.JLabel DriversPanel_Icon;
    private javax.swing.JLabel DriversPanel_Icon1;
    private javax.swing.JLabel DriversPanel_Icon2;
    private javax.swing.JLabel DriversPanel_Icon3;
    private javax.swing.JPanel IDriverPanel5;
    private javax.swing.JPanel IDriverPanel6;
    private javax.swing.JPanel IDriverPanel7;
    private javax.swing.JLabel IDriversPanel_Data;
    private javax.swing.JLabel IDriversPanel_Data1;
    private javax.swing.JLabel IDriversPanel_Data2;
    private javax.swing.JLabel IDriversPanel_Data3;
    private javax.swing.JLabel IDriversPanel_Title;
    private javax.swing.JLabel IDriversPanel_Title1;
    private javax.swing.JLabel IDriversPanel_Title2;
    private javax.swing.JLabel IDriversPanel_Title3;
    private javax.swing.JPanel IInfractionPanel;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
